version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      time: "20:00"
      timezone: Europe/Paris
    reviewers:
      - Guts
    labels:
      - ci-cd
